# Generated by Django 5.2.12 on 2026-03-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Name of the skill category.', max_length=100)),
                ('category_code', models.CharField(db_index=True, help_text='Unique short code for the category.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete switch.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'skill_category_master',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillLevelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(help_text='Display name for the proficiency level.', max_length=50)),
                ('level_rank', models.PositiveSmallIntegerField(help_text='Numeric rank used for skill gap analysis calculations (e.g. 1-5).')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Level',
                'verbose_name_plural': 'Skill Levels',
                'db_table': 'skill_level_master',
                'ordering': ['level_rank'],
                'indexes': [models.Index(fields=['level_rank'], name='idx_skill_level_rank')],
            },
        ),
        migrations.CreateModel(
            name='SkillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the skill.', max_length=150)),
                ('skill_code', models.CharField(db_index=True, help_text='Unique identifier for the skill.', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete switch.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_skill', models.ForeignKey(blank=True, help_text='Parent skill for hierarchical structure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_skills', to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skill_master',
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_history', to='org_management.employeemaster')),
                ('new_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_history', to='skill_management.skilllevelmaster')),
                ('old_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_history', to='skill_management.skilllevelmaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Employee Skill History',
                'verbose_name_plural': 'Employee Skill Histories',
                'db_table': 'employee_skill_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.BigIntegerField(help_text='Reference to future AssessmentMaster ID.')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score achieved in the assessment.', max_digits=5)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='org_management.employeemaster')),
                ('result_level', models.ForeignKey(help_text='Skill proficiency level awarded based on the score.', on_delete=django.db.models.deletion.PROTECT, to='skill_management.skilllevelmaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Employee Skill Assessment',
                'verbose_name_plural': 'Employee Skill Assessments',
                'db_table': 'employee_skill_assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategorySkillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='skill_management.skillcategorymaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Skill-Category Mapping',
                'verbose_name_plural': 'Skill-Category Mappings',
                'db_table': 'skill_category_skill_map',
                'unique_together': {('skill', 'category')},
            },
        ),
        migrations.CreateModel(
            name='JobRoleSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(help_text='Role being assigned the skill requirement.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='org_management.jobrolemaster')),
                ('required_level', models.ForeignKey(help_text='Minimum proficiency level required for this role.', on_delete=django.db.models.deletion.PROTECT, to='skill_management.skilllevelmaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Job Role Skill Requirement',
                'verbose_name_plural': 'Job Role Skill Requirements',
                'db_table': 'job_role_skill_requirement',
                'unique_together': {('job_role', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='org_management.employeemaster')),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skill_management.skilllevelmaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_owners', to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'db_table': 'employee_skill',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CourseSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(help_text='Reference to future CourseMaster ID.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_level', models.ForeignKey(help_text='The proficiency level expected after completing this course.', on_delete=django.db.models.deletion.PROTECT, to='skill_management.skilllevelmaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='skill_management.skillmaster')),
            ],
            options={
                'verbose_name': 'Course Skill Mapping',
                'verbose_name_plural': 'Course Skill Mappings',
                'db_table': 'course_skill_mapping',
                'unique_together': {('course_id', 'skill')},
            },
        ),
    ]
