# Generated by Django 5.2.12 on 2026-04-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSkillMapping',
        ),
    ]
