# Generated by Django 5.2.12 on 2026-05-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0002_jobrolemaster_company_and_more'),
        ('skill_management', '0003_tni_rating_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeskillrating',
            name='uniq_employee_skill_rating_type',
        ),
        migrations.AlterField(
            model_name='employeeskillrating',
            name='accomplishments',
            field=models.TextField(blank=True, default='', help_text='Recent accomplishments (used for SELF ratings).'),
        ),
        migrations.AlterField(
            model_name='employeeskillrating',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Reviewer notes (used for MANAGER ratings).', max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeskillrating',
            name='observations',
            field=models.TextField(blank=True, default='', help_text='Observed performance hindrances (used for SELF ratings).'),
        ),
        migrations.AlterField(
            model_name='employeeskillrating',
            name='rated_by',
            field=models.ForeignKey(help_text='The person who performed the rating (employee for SELF, manager for MANAGER).', on_delete=django.db.models.deletion.CASCADE, related_name='given_skill_ratings', to='org_management.employeemaster'),
        ),
        migrations.AlterField(
            model_name='employeeskillratinghistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this history entry was recorded.'),
        ),
        migrations.AlterField(
            model_name='employeeskillratinghistory',
            name='new_status',
            field=models.CharField(help_text='Status after this change.', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeskillratinghistory',
            name='notes_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot of notes/observations at the time of this change.', max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeskillratinghistory',
            name='old_status',
            field=models.CharField(blank=True, default='', help_text='Status before this change.', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='employeeskillrating',
            unique_together={('employee', 'skill', 'rating_type')},
        ),
    ]
