# Generated by Django 5.2.12 on 2026-03-24 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Full legal name of the company.', max_length=255)),
                ('company_code', models.CharField(db_index=True, help_text='Unique short code for the company (e.g. OTL).', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Master on/off switch for company data across system.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'org_company_master',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['company_code'], name='idx_company_master_code')],
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_unit_name', models.CharField(help_text='Name of the business unit.', max_length=255)),
                ('business_unit_code', models.CharField(help_text='Short code for the business unit.', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='org_management.companymaster')),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
                'db_table': 'org_business_unit_master',
                'ordering': ['business_unit_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='Name of the department.', max_length=255)),
                ('department_code', models.CharField(help_text='Short code for the department.', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='org_management.businessunitmaster')),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department if this is a sub-department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='org_management.departmentmaster')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'org_department_master',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(db_index=True, help_text='Unique employee identifier (Employee ID).', max_length=50, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org_management.businessunitmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org_management.companymaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org_management.departmentmaster')),
                ('user', models.ForeignKey(blank=True, help_text='Link to authentication user account. Null if account is not yet created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'org_employee_master',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeReportingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('DIRECT', 'Direct'), ('DOTTED', 'Dotted')], default='DIRECT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='org_management.employeemaster')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='org_management.employeemaster')),
            ],
            options={
                'verbose_name': 'Reporting Manager Mapping',
                'verbose_name_plural': 'Reporting Manager Mappings',
                'db_table': 'org_employee_reporting_manager',
            },
        ),
        migrations.CreateModel(
            name='JobRoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role_name', models.CharField(help_text='Job role / Designation title.', max_length=255)),
                ('job_role_code', models.CharField(db_index=True, help_text='Unique short code for the designation.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'db_table': 'org_job_role_master',
                'ordering': ['job_role_name'],
                'indexes': [models.Index(fields=['job_role_code'], name='idx_job_role_code')],
            },
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org_management.jobrolemaster'),
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='Name of the location / branch.', max_length=255)),
                ('location_code', models.CharField(help_text='Internal code for the branch.', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='org_management.companymaster')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'org_location_master',
                'ordering': ['location_name'],
            },
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org_management.locationmaster'),
        ),
        migrations.AddIndex(
            model_name='businessunitmaster',
            index=models.Index(fields=['company'], name='idx_bu_company_id'),
        ),
        migrations.AddIndex(
            model_name='businessunitmaster',
            index=models.Index(fields=['business_unit_code'], name='idx_bu_code'),
        ),
        migrations.AlterUniqueTogether(
            name='businessunitmaster',
            unique_together={('company', 'business_unit_code')},
        ),
        migrations.AddIndex(
            model_name='departmentmaster',
            index=models.Index(fields=['business_unit'], name='idx_dept_bu_id'),
        ),
        migrations.AddIndex(
            model_name='departmentmaster',
            index=models.Index(fields=['department_code'], name='idx_dept_code'),
        ),
        migrations.AddIndex(
            model_name='departmentmaster',
            index=models.Index(fields=['parent_department'], name='idx_dept_parent_id'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentmaster',
            unique_together={('business_unit', 'department_code')},
        ),
        migrations.AddIndex(
            model_name='employeereportingmanager',
            index=models.Index(fields=['employee'], name='idx_rep_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeereportingmanager',
            index=models.Index(fields=['manager'], name='idx_rep_manager_id'),
        ),
        migrations.AlterUniqueTogether(
            name='employeereportingmanager',
            unique_together={('employee', 'manager', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='locationmaster',
            index=models.Index(fields=['company'], name='idx_loc_company_id'),
        ),
        migrations.AddIndex(
            model_name='locationmaster',
            index=models.Index(fields=['location_code'], name='idx_loc_code'),
        ),
        migrations.AlterUniqueTogether(
            name='locationmaster',
            unique_together={('company', 'location_code')},
        ),
        migrations.AddIndex(
            model_name='employeemaster',
            index=models.Index(fields=['employee_code'], name='idx_emp_code'),
        ),
        migrations.AddIndex(
            model_name='employeemaster',
            index=models.Index(fields=['company'], name='idx_emp_company'),
        ),
        migrations.AddIndex(
            model_name='employeemaster',
            index=models.Index(fields=['department'], name='idx_emp_dept'),
        ),
        migrations.AddIndex(
            model_name='employeemaster',
            index=models.Index(fields=['job_role'], name='idx_emp_role'),
        ),
    ]
