# Generated by Django 5.2.12 on 2026-04-17 10:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0002_coursecontent_file_ref_courseresource_file_ref'),
        ('file_management', '0001_initial'),
        ('org_management', '0002_jobrolemaster_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Single Choice (MCQ)'), ('MSQ', 'Multiple Select (MSQ)'), ('TRUE_FALSE', 'True/False'), ('DESCRIPTIVE', 'Descriptive / Long Answer'), ('SCENARIO', 'Scenario-based Question'), ('FILE_UPLOAD', 'File Upload Assignment')], default='MCQ', max_length=50)),
                ('scenario_text', models.TextField(blank=True, default='', help_text='The prompt or context for scenario-based questions.')),
                ('explanation_text', models.TextField(blank=True, default='', help_text='Shown to students after submission for learning purposes.')),
                ('difficulty_complexity', models.PositiveIntegerField(default=1, help_text='1 (Easy) to 5 (Expert)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asmt_question_bank',
            },
        ),
        migrations.CreateModel(
            name='AssessmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Time limit in minutes.')),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('retake_limit', models.PositiveIntegerField(default=1, help_text='Number of times a student can attempt this quiz.')),
                ('is_randomized', models.BooleanField(default=False, help_text='If true, question order will be shuffled for each student.')),
                ('negative_marking_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of question weight to deduct for wrong answers.', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course_management.coursemaster')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='course_management.courselesson')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'asmt_master',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Calculated based on duration_minutes at start.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='IN_PROGRESS', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='org_management.employeemaster')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment_engine.assessmentmaster')),
            ],
            options={
                'db_table': 'asmt_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending Review')], default='PENDING', max_length=50)),
                ('grading_type', models.CharField(choices=[('PENDING', 'Pending Manual Review'), ('AUTO_GRADED', 'Auto Graded'), ('MANUALLY_GRADED', 'Manually Graded')], default='PENDING', max_length=50)),
                ('instructor_feedback', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment_engine.assessmentattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'asmt_result',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('feedback_text', models.TextField(blank=True, default='', help_text='Specific feedback if this option is chosen.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment_engine.questionbank')),
            ],
            options={
                'db_table': 'asmt_question_option',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_points', models.DecimalField(decimal_places=2, default=1.0, help_text='How many points this question is worth in this specific assessment.', max_digits=5)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='assessment_engine.assessmentmaster')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_usages', to='assessment_engine.questionbank')),
            ],
            options={
                'db_table': 'asmt_question_mapping',
                'ordering': ['display_order'],
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('is_auto_graded', models.BooleanField(default=False)),
                ('earned_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment_engine.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessment_engine.questionbank')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment_engine.questionoption')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_management.fileregistry')),
            ],
            options={
                'db_table': 'asmt_user_answer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
