# Generated by Django 5.2.12 on 2026-04-17 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmaster',
            name='negative_marking_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of question weight to deduct for wrong answers.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
