# Generated by Django 5.2.12 on 2026-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_engine', '0002_alter_assessmentmaster_negative_marking_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='assessmentmaster',
            name='negative_marking_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, incorrect answers will deduct points based on the percentage below.'),
        ),
        migrations.AddField(
            model_name='assessmentquestionmapping',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time limit for this specific question in seconds. 0 for unlimited.'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='user_answers', to='assessment_engine.questionoption'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='status',
            field=models.CharField(choices=[('NOT_VISITED', 'Not Visited'), ('ATTEMPTED', 'Attempted'), ('TIMED_OUT', 'Timed Out')], default='NOT_VISITED', max_length=20),
        ),
    ]
