# Generated by Django 5.2.12 on 2026-03-24 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Name of the permission group.', max_length=255)),
                ('group_code', models.CharField(db_index=True, help_text='Unique short code for the permission group.', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which this group appears in the UI.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
                'db_table': 'rbac_permission_group_master',
                'ordering': ['display_order', 'group_name'],
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='Name of the role.', max_length=255)),
                ('role_code', models.CharField(db_index=True, help_text='Unique short code for the role.', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_system_role', models.BooleanField(default=False, help_text='Indicates if this is a default system role that cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'rbac_role_master',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(help_text='Human-readable name of the permission.', max_length=255)),
                ('permission_code', models.CharField(db_index=True, help_text='Unique exact permission string evaluated in code (e.g., USER_DELETE).', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.permissiongroupmaster')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'rbac_permission_master',
                'ordering': ['permission_group__display_order', 'permission_name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permissionmaster')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.rolemaster')),
            ],
            options={
                'verbose_name': 'Role Permission Mapping',
                'verbose_name_plural': 'Role Permission Mappings',
                'db_table': 'rbac_role_permission_master',
            },
        ),
        migrations.CreateModel(
            name='UserRoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('COMPANY', 'Company'), ('BUSINESS_UNIT', 'Business Unit'), ('DEPARTMENT', 'Department'), ('SELF', 'Self')], default='GLOBAL', help_text='The boundary where this role applies (e.g., GLOBAL, DEPARTMENT).', max_length=50)),
                ('scope_id', models.IntegerField(blank=True, help_text='The ID of the scope entity (e.g., Department ID). Null if scope is GLOBAL or SELF.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.rolemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'rbac_user_role_master',
            },
        ),
        migrations.AddIndex(
            model_name='permissionmaster',
            index=models.Index(fields=['permission_code'], name='idx_perm_code'),
        ),
        migrations.AddIndex(
            model_name='permissionmaster',
            index=models.Index(fields=['permission_group'], name='idx_perm_group_id'),
        ),
        migrations.AddIndex(
            model_name='rolepermissionmaster',
            index=models.Index(fields=['role'], name='idx_role_perm_role_id'),
        ),
        migrations.AddIndex(
            model_name='rolepermissionmaster',
            index=models.Index(fields=['permission'], name='idx_role_perm_perm_id'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionmaster',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrolemaster',
            index=models.Index(fields=['user'], name='idx_user_role_user_id'),
        ),
        migrations.AddIndex(
            model_name='userrolemaster',
            index=models.Index(fields=['role'], name='idx_user_role_role_id'),
        ),
        migrations.AddIndex(
            model_name='userrolemaster',
            index=models.Index(fields=['scope_type', 'scope_id'], name='idx_user_role_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='userrolemaster',
            unique_together={('user', 'role', 'scope_type', 'scope_id')},
        ),
    ]
