// All known permission codes from the RBAC module.

export const PERMISSIONS = {
  // User Management (group: USER_MGMT)
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',

  // RBAC Management (group: RBAC_MGMT)
  ROLE_VIEW: 'ROLE_VIEW',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',

  // System Configuration (group: SYS_CONFIG)
  CONFIG_VIEW: 'CONFIG_VIEW',

  // Skill Management (group: SKILL_MGMT)
  SKILL_CATEGORY_MANAGE: 'SKILL_CATEGORY_MANAGE',
  SKILL_MANAGE: 'SKILL_MANAGE',
  SKILL_MAPPING_MANAGE: 'SKILL_MAPPING_MANAGE',
  SKILL_LEVEL_MANAGE: 'SKILL_LEVEL_MANAGE',
  ROLE_COMPETENCY_MANAGE: 'ROLE_COMPETENCY_MANAGE',
  EMPLOYEE_SKILL_MANAGE: 'EMPLOYEE_SKILL_MANAGE',
  EMPLOYEE_SKILL_HISTORY_VIEW: 'EMPLOYEE_SKILL_HISTORY_VIEW',
  SKILL_ASSESSMENT_MANAGE: 'SKILL_ASSESSMENT_MANAGE',
  COURSE_SKILL_MANAGE: 'COURSE_SKILL_MANAGE',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];
