# Generated by Django 5.2.12 on 2026-04-04 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_management', '0001_initial'),
        ('skill_management', '0002_delete_courseskillmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course_lesson',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'course_category_master',
                'indexes': [models.Index(fields=['category_code'], name='idx_crs_cat_code')],
            },
        ),
        migrations.CreateModel(
            name='CourseDiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(max_length=255)),
                ('thread_body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_management.employeemaster')),
            ],
            options={
                'db_table': 'course_discussion_thread',
            },
        ),
        migrations.CreateModel(
            name='CourseDiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_management.employeemaster')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='course_management.coursediscussionthread')),
            ],
            options={
                'db_table': 'course_discussion_reply',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('PPT', 'PPT'), ('DOCUMENT', 'Document'), ('LINK', 'External Link'), ('QUIZ', 'Quiz')], default='VIDEO', max_length=50)),
                ('content_url', models.URLField(blank=True, default='', max_length=500)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course_management.courselesson')),
            ],
            options={
                'db_table': 'course_content',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=50)),
                ('estimated_duration_hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='course_management.coursecategorymaster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_courses', to='org_management.employeemaster')),
            ],
            options={
                'verbose_name': 'Course Master',
                'verbose_name_plural': 'Course Masters',
                'db_table': 'course_master',
            },
        ),
        migrations.AddField(
            model_name='coursediscussionthread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='course_management.coursemaster'),
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=200)),
                ('resource_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='course_management.coursemaster')),
            ],
            options={
                'db_table': 'course_resource',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=150)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course_management.coursemaster')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'db_table': 'course_section',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='courselesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_management.coursesection'),
        ),
        migrations.CreateModel(
            name='CourseSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skilled_outcomes', to='course_management.coursemaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_management.skillmaster')),
                ('target_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skill_management.skilllevelmaster')),
            ],
            options={
                'db_table': 'course_skill_mapping',
            },
        ),
        migrations.CreateModel(
            name='TagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag Master',
                'verbose_name_plural': 'Tag Masters',
                'db_table': 'course_tag_master',
                'indexes': [models.Index(fields=['tag_name'], name='idx_crs_tag_name')],
            },
        ),
        migrations.CreateModel(
            name='CourseTagMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='course_management.coursemaster')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.tagmaster')),
            ],
            options={
                'db_table': 'course_tag_map',
            },
        ),
        migrations.AddIndex(
            model_name='coursemaster',
            index=models.Index(fields=['course_code'], name='idx_crs_master_code'),
        ),
        migrations.AddIndex(
            model_name='coursemaster',
            index=models.Index(fields=['category'], name='idx_crs_master_cat_id'),
        ),
        migrations.AlterUniqueTogether(
            name='courseskillmapping',
            unique_together={('course', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='coursetagmap',
            unique_together={('course', 'tag')},
        ),
    ]
