# Generated by Django 5.2.12 on 2026-04-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0001_initial'),
        ('tni_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgapsnapshot',
            name='current_level',
            field=models.ForeignKey(blank=True, help_text="The employee's proficiency level at the time of detection.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gap_current_snapshots', to='skill_management.skilllevelmaster'),
        ),
    ]
