# Generated by Django 5.2.12 on 2026-04-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        ('org_management', '0001_initial'),
        ('tni_management', '0002_alter_skillgapsnapshot_current_level'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='compliancetrainingrequirement',
            name='idx_compliance_course_id',
        ),
        migrations.RemoveIndex(
            model_name='trainingneedcourserecommendation',
            name='idx_tni_course_course_id',
        ),
        migrations.RemoveField(
            model_name='compliancetrainingrequirement',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='trainingneedcourserecommendation',
            name='course_id',
        ),
        migrations.AddField(
            model_name='compliancetrainingrequirement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_requirements', to='course_management.coursemaster'),
        ),
        migrations.AddField(
            model_name='trainingneedcourserecommendation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tni_recommendations', to='course_management.coursemaster'),
        ),
        migrations.AddIndex(
            model_name='compliancetrainingrequirement',
            index=models.Index(fields=['course'], name='idx_compliance_course_fk'),
        ),
        migrations.AddIndex(
            model_name='trainingneedcourserecommendation',
            index=models.Index(fields=['course'], name='idx_tni_course_course_fk'),
        ),
    ]
