# Generated by Django 5.2.12 on 2026-04-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        ('tni_management', '0003_remove_compliancetrainingrequirement_idx_compliance_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancetrainingrequirement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_requirements', to='course_management.coursemaster'),
        ),
        migrations.AlterField(
            model_name='trainingneedcourserecommendation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tni_recommendations', to='course_management.coursemaster'),
        ),
    ]
