# Generated by Django 5.2.12 on 2026-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tni_management', '0005_rename_approved_at_actioned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingneedapproval',
            name='actioned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the approval action was finalized (approve or reject).', null=True),
        ),
    ]
