# Generated by Django 5.2.12 on 2026-04-04 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_management', '0001_initial'),
        ('org_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=200)),
                ('path_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'db_table': 'lp_master',
            },
        ),
        migrations.CreateModel(
            name='UserCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('SELF_ENROLL', 'Self Enrolled'), ('MANDATORY', 'Mandatory Assignment'), ('RECOMMENDED', 'Recommended by Manager'), ('TNI_ASSIGNED', 'TNI Gap Closure')], default='SELF_ENROLL', max_length=50)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='NOT_STARTED', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_enrollments', to='course_management.coursemaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='org_management.employeemaster')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_progress.learningpathmaster')),
            ],
            options={
                'db_table': 'lp_user_course_enrollment',
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learning_progress.usercourseenrollment')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'lp_course_certificate',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='NOT_STARTED', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='learning_progress.usercourseenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course_management.courselesson')),
            ],
            options={
                'db_table': 'lp_user_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='UserContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playhead_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course_management.coursecontent')),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='learning_progress.userlessonprogress')),
            ],
            options={
                'db_table': 'lp_user_content_progress',
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.coursemaster')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learning_progress.learningpathmaster')),
            ],
            options={
                'db_table': 'lp_course_map',
                'ordering': ['display_order'],
                'unique_together': {('path', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['employee', 'status'], name='idx_lp_enroll_emp_status'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseenrollment',
            unique_together={('employee', 'course', 'learning_path')},
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='usercontentprogress',
            unique_together={('lesson_progress', 'content')},
        ),
    ]
