# Generated by Django 5.2.12 on 2026-04-03 13:29

import common.methods
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=common.methods.current_year, help_text='Training Calendar year (YYYY format).', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_management.employeemaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_calendars', to='org_management.departmentmaster')),
            ],
            options={
                'verbose_name': 'Training Calendar',
                'verbose_name_plural': 'Training Calendars',
                'db_table': 'tp_training_calendar',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='Title of the training plan.', max_length=255)),
                ('year', models.PositiveIntegerField(default=common.methods.current_year, help_text='Training Plan year (YYYY format).', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='org_management.employeemaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='org_management.departmentmaster')),
            ],
            options={
                'verbose_name': 'Training Plan',
                'verbose_name_plural': 'Training Plans',
                'db_table': 'tp_training_plan',
                'ordering': ['-year', 'plan_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('comments', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_approvals', to='org_management.employeemaster')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='training_planning.trainingplan')),
            ],
            options={
                'verbose_name': 'Training Plan Approval',
                'verbose_name_plural': 'Training Plan Approvals',
                'db_table': 'tp_training_plan_approval',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(help_text='Reference to future CourseMaster(id).')),
                ('planned_participants', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_plan_items', to='org_management.departmentmaster')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training_planning.trainingplan')),
            ],
            options={
                'verbose_name': 'Training Plan Item',
                'verbose_name_plural': 'Training Plan Items',
                'db_table': 'tp_training_plan_item',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(help_text='Reference to future CourseMaster(id).')),
                ('session_title', models.CharField(help_text='Batch name (e.g. Batch 1, Special Workshop).', max_length=255)),
                ('session_type', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid'), ('SELF_PACED', 'Self Paced')], default='ONLINE', max_length=50)),
                ('session_start_date', models.DateTimeField()),
                ('session_end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', help_text='Physical room or venue.', max_length=255)),
                ('meeting_link', models.URLField(blank=True, default='', help_text='Zoom/Teams/Meet link for Online sessions.', max_length=500)),
                ('capacity', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training_planning.trainingcalendar')),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'db_table': 'tp_training_session',
                'ordering': ['session_start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PARTIAL', 'Partial')], default='PRESENT', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='org_management.employeemaster')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='training_planning.trainingsession')),
            ],
            options={
                'verbose_name': 'Training Attendance',
                'verbose_name_plural': 'Training Attendance Logs',
                'db_table': 'tp_training_attendance',
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLIST', 'Waitlist'), ('CANCELLED', 'Cancelled')], default='ENROLLED', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_enrollments', to='org_management.employeemaster')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training_planning.trainingsession')),
            ],
            options={
                'verbose_name': 'Session Enrollment',
                'verbose_name_plural': 'Session Enrollments',
                'db_table': 'tp_training_session_enrollment',
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sessions', to='org_management.employeemaster')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='training_planning.trainingsession')),
            ],
            options={
                'verbose_name': 'Session Trainer',
                'verbose_name_plural': 'Session Trainers',
                'db_table': 'tp_training_session_trainer',
            },
        ),
        migrations.AddIndex(
            model_name='trainingcalendar',
            index=models.Index(fields=['year'], name='idx_tp_calendar_year'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingcalendar',
            unique_together={('year', 'department')},
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['department'], name='idx_tp_plan_dept_id'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['year'], name='idx_tp_plan_year'),
        ),
        migrations.AddIndex(
            model_name='trainingplanapproval',
            index=models.Index(fields=['training_plan'], name='idx_tp_approval_plan_id'),
        ),
        migrations.AddIndex(
            model_name='trainingplanapproval',
            index=models.Index(fields=['approver'], name='idx_tp_approval_approver_id'),
        ),
        migrations.AddIndex(
            model_name='trainingplanitem',
            index=models.Index(fields=['training_plan'], name='idx_tp_item_plan_id'),
        ),
        migrations.AddIndex(
            model_name='trainingplanitem',
            index=models.Index(fields=['course_id'], name='idx_tp_item_course_id'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['course_id'], name='idx_tp_session_course_id'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['calendar'], name='idx_tp_session_cal_id'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['session_start_date'], name='idx_tp_session_start'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['training_session'], name='idx_tp_attn_session_id'),
        ),
        migrations.AddIndex(
            model_name='trainingattendance',
            index=models.Index(fields=['employee'], name='idx_tp_attn_emp_id'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('training_session', 'employee')},
        ),
        migrations.AddIndex(
            model_name='trainingsessionenrollment',
            index=models.Index(fields=['training_session'], name='idx_tp_enroll_session_id'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionenrollment',
            index=models.Index(fields=['employee'], name='idx_tp_enroll_emp_id'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingsessionenrollment',
            unique_together={('training_session', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsessiontrainer',
            unique_together={('training_session', 'trainer')},
        ),
    ]
