# Generated by Django 5.2.12 on 2026-04-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        ('org_management', '0001_initial'),
        ('training_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingplanitem',
            name='idx_tp_item_course_id',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='idx_tp_session_course_id',
        ),
        migrations.RemoveField(
            model_name='trainingplanitem',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='course_id',
        ),
        migrations.AddField(
            model_name='trainingplanitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='course_management.coursemaster'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course_management.coursemaster'),
        ),
        migrations.AddIndex(
            model_name='trainingplanitem',
            index=models.Index(fields=['course'], name='idx_tp_item_course_fk'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['course'], name='idx_tp_session_course_fk'),
        ),
    ]
