# Generated by Django 5.2.12 on 2026-04-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
        ('training_planning', '0002_remove_trainingplanitem_idx_tp_item_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplanitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='course_management.coursemaster'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='course_management.coursemaster'),
        ),
    ]
